name: auto gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 配置 ssh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com > ~/.ssh/known_hosts
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
          git config --global user.email "990834867@qq.com"
          git config --global user.name "ouzhou"

      - name: 切到 master
        uses: actions/checkout@master

      - name: 安装 nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: 安装 node_modules
        run: npm install

      - name: 构建
        run: npm run build

      - name: 发布
        run: |
          git checkout --orphan gh-temp
          echo "node_modules\n.umi\n.umi-production" > .gitignore   
          git add .
          git commit -am "auto commit"
          git subtree split --prefix dist -b gh-pages
          git push -f origin gh-pages:gh-pages

