name: auto gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 切到master
        uses: actions/checkout@master

      - name: 安装nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: 安装node_modules
        run: npm install

      - name: 发布
        run: npm run deploy
